// examples/user-management/react-user-management/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'
import { tealbase } from './tealbaseClient'
import Auth from './Auth'
import Account from './Account'

function App() {
  const [session, setSession] = useState(null)

  useEffect(() => {
    tealbase.auth.getSession().then(({ data: { session } }) => {
      setSession(session)
    })

    const { data } = tealbase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })

    return () => data.subscription.unsubscribe();
  }, [])

  return (
    <div className="container" style={{ padding: '50px 0 100px 0' }}>
      {!session ? <Auth /> : <Account key={session.user.id} session={session} />}
    </div>
  )
}

export default App

// examples/user-management/solid-user-management/src/App.tsx
import { Component, createEffect, createSignal } from 'solid-js'
import { tealbase } from './tealbaseClient'
import { AuthSession } from '@tealbase/tealbase-js'
import Account from './Account'
import Auth from './Auth'

const App: Component = () => {
	const [session, setSession] = createSignal<AuthSession | null>(null)

	createEffect(() => {
		tealbase.auth.getSession().then(({ data: { session } }) => {
			setSession(session)
		})

		tealbase.auth.onAuthStateChange((_event, session) => {
			setSession(session)
		})
	})

	return (
		<div class="container" style={{ padding: '50px 0 100px 0' }}>
			{!session() ? <Auth /> : <Account session={session()!} />}
		</div>
	)
}

export default App
